### ISSUE TITLE
Several TODO tasks

### ISSUE THREAD

**Issue by jermainewang** [VoVAllen/tf-dlpack#1] opened 2019-11-06 17:11 UTC
@VoVAllen 
* Add CI to the project. Just use travis should be fine.
* Lint check from dmlc-core. You could follow the setup in dgl.
* More tests.
  - We should test the case when A->B and then A goes out-of-scope.
  - Different devices (CPU, GPU tests)
* Look like FromDLPack does not support data types other than float.

Also, what's the problem of inheriting TF's allocator?

**Comment by VoVAllen** [comment] 2019-11-06 17:30
I just fixed FromDLPack (https://github.com/VoVAllen/tf-dlpack/blob/master/src/from_dlpack_kernel_copy.cc#L67)

The problem is the output tensor has to be create with `context->allocate_output` at [here](https://github.com/VoVAllen/tf-dlpack/blob/master/src/from_dlpack_kernel_copy.cc#L39). 
There's no problem inheriting TF's allocator, and it works well. But you cannot set the tensor created with `new Tensor(allocator...)` as the output. 
All context function can be found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.h#L608). `set_output` will copy the tensor(created with new Tensor), and `set_output_ref` is not supported in tf 2.0.

**Comment by VoVAllen** [comment] 2019-11-06 17:33
Also I found pytorch will also copy the `from_dlpack` tensor when doing further computation. 
You can verify this with cupy's dlpack. Allocate a big enough tensor and send to torch with dlpack. You would find no copy is invoked when `torch.utils.data.from_dlpack`. But when you print it or doing other operation on it(such as b=a+1), it will copy the tensor. (You can see memory doubled with nvidia-smi)

**Comment by VoVAllen** [comment] 2019-11-06 17:34
Currently I tested scope with https://github.com/VoVAllen/tf-dlpack/blob/master/test/test_to_dlpack.py#L5.

**Comment by jermainewang** [comment] 2019-11-06 17:34
> Also I found pytorch will also copy the `from_dlpack` tensor when doing further computation.
> You can verify this with cupy's dlpack. Allocate a big enough tensor and send to torch with dlpack. You would find no copy is invoked when `torch.utils.data.from_dlpack`. But when you print it or doing other operation on it(such as b=a+1), it will copy the tensor. (You can see memory doubleed with nvidia-smi)

Shouldn't the memory be doubled since `b` is a new tensor?

**Comment by VoVAllen** [comment] 2019-11-06 17:35
No. if you do b=a+1, the memory triples.

**Comment by jermainewang** [comment] 2019-11-06 17:49
That might be a problem. DGL uses DLPack a lot. Could you try locate the code to double check?

**Comment by VoVAllen** [comment] 2019-11-07 11:50
Update: I checked your implementation, it seems zero copy based on gpu memory usage. And I just change file at my side.
Test file: https://github.com/VoVAllen/tf-dlpack/blob/master/test/test_zero_copy.py

Also I found way to avoid cudaMemcpy in `to_dlpack`. Therefore we don't need cuda runtime anymore. The cuda dependency is removed.

But calling deleter in `DeallocateRaw` still leads to core dump. I'm trying to figure out why. 

C++ code is almost done. Could you help check whether the libpath in `setup.py` works?

**Comment by VoVAllen** [comment] 2019-11-07 11:52
I'm working on test, lint and CI now.

**Comment by VoVAllen** [comment] 2019-11-07 11:56
> But calling deleter in DeallocateRaw still leads to core dump. I'm trying to figure out why.

I forgot to set capsule's deconstructor. Should be fixed now.

**Comment by VoVAllen** [comment] 2019-11-07 15:28
test和lint都搞好了，就差CI了

**Comment by jermainewang** [comment] 2019-11-08 17:21
Missing license file. Does TF use Apache 2.0?

**Comment by VoVAllen** [comment] 2019-11-08 17:28
Yes. I added the apache license to our repo.

**Closed as completed** 2019-11-09 09:33 UTC
